### PR TITLE
Schedule Date Parsing REST Endpoint

### PR DESCRIPTION
**Pull request by calebpanza**
# Schedule Date Parsing Endpoint
This PR adds an additional REST endpoint that helps to parse Rock Schedule iCalendar strings into Date/Time occurrences.

**Endpoint:** `/api/Apollos/Schedules/ParseDates/{scheduleId}`
**Inputs**:
`scheduleId`: Integer ID of the schedule you'd like to parse
`startTime`: DateTime that indicates the start of the range you'd like to get schedule occurrences for
`endTime`: DateTime that indicates the end of the range you'd like to get schedule occurrences for

### What is this endpoint for?
Rock stores schedules as an iCalendar string. In my personal attempts at parsing them, I've noticed some things that seem to be unique to Rock in the way that the iCal string is created. In order to more accurately and quickly parse iCal strings for the purposes of Groups and Events, this endpoint exposes Rock's internal iCalendar parsing method to the REST API for quick and easy parsing.

### Tradeoffs and Design Decisions
* This method requires an iCalendar string to be present on the given Schedule, so it will _not_ parse Rock's "weekly" schedule type. Custom and Named schedules are completely supported
* This is not an `IQueryable` endpoint because it does not return a Rock Entity type. For speed and efficiency, there is also included a small struct called `ScheduleOccurrence` which stores a `StartTime` and `EndTime` which indicates the duration of a specific Schedule Occurrence. Again, the purpose of this endpoint is to be a fast utility for parsing schedules, NOT for looking up schedules

### Testing
Build the Plugin and copy the `dll`'s into Rock. Load up the API and pass in a schedule id. While Rock's `GetICalOccurrences` allows `endTime` as an optional parameter, I've found that most schedules only return data when both a `startTime` _and_ `endTime` are given.

**_The following schedule variations/types have been tested:_**
Daily Schedules: ✅
Weekly Schedules: ✅
Monthly Schedules: ✅
Single Date Schedules: ✅
Select Specific Dates: ✅
Daily Schedule with Date Exclusions: ✅

---

_please note:_ this enhancement originated from Christ Fellowship's attempts to replicate Rock's iCalendar parsing from their GraphQL API. The amount of code it took was roughly 500 lines and was still not accurate in some cases with TimeZones and exceptions to the schedules like excluded dates. Should Apollos ever want to enable a more robust use of the Rock Schedule entity, I would greatly encourage considering this code for easier maintenance

### CODE REVIEW

**Comment by richarddubay** [comment]
Screen Shot 2022-05-21 at 6 11 11 PM

Looks like this works. I made some changes locally to it to get it to work with NewSpring's latest `alpha` build (which I think is a v14 build), which makes me feel like it would work on earlier Rock versions as well. I'd be happy to wrap this up into the first v13 build if this is something that we think would be of benefit to the folks using the plugin.

@conrad-vanl @vinnyjth If one of y'all could give me a 👍🏼 or 👎🏼 on whether or not y'all would like this added to the plugin, I can proceed accordingly.

Oh, I also suppose maybe we should change it to return an `IQueryable<ScheduleOccurence[]>` so that we can take advantage of filtering, sorting, and such. @calebpanza is that something you can do?

**Comment by calebpanza** [comment]
@richarddubay I see what you're saying. Do we see a valid use case in which we would want to do additional filtering or a non-linear sorting? I know that all use cases at CF are looking for a linear sort with the Rock Schedule providing all the "filtering" of dates/times.

Just a thought before trying to figure out how to get a Windows VM spun up to update it

**Comment by richarddubay** [comment]
@calebpanza Not sure. I just happened to notice that every other endpoint in the plugin has the option for filtering and such. We can always come back and add it later I suppose if it's something that we end up deciding would be beneficial or we find a use case for.

**Comment by richarddubay** [comment]
@conrad-vanl @vinnyjth Still waiting on a 👍🏼 or 👎🏼 from one of y'all on whether you want this in the plugin. cc: @calebpanza

**Pull request closed without merging**
